### ISSUE TITLE
[Enhancement][Relay] Add switch in callContract method in TransactionManager to decide execute txn right now

### ISSUE THREAD

**Issue by Lisooo790926** [social-tw/social-tw-website#254]
**Is your feature request related to a problem? Please describe.**
Follow @chentihe advice we could modify TransactionManager callContract method
can we modify the callContract method by adding a flag to decide this tx is executing right now or not?
I think this will be more readable.
p.s. the appContract variable in callContract method can be retrieved by this.appContract, also the address of the contract can be retrieved by appContract.address

**Additional context**
Link PR #249

**Comment by ryanycw** [comment]
joining the discussion

**Comment by chentihe** [comment]
Update the content of issue which is discussed on 2024/4/26.

- TransactionManager
  - refactor the error to InternalError and move to InternalError.ts under type folder
  - the `appContract` variable in callContract method can be retrieved by `this.appContract`, also, the address of the contract can be retrieved by `appContract.address`
  - since all transactions will be queued, so there's no need to add a flag argument to decide this transaction executes immediately or not.
- UserService
  - the interaction with contract on signup function can be replaced with `callContract` function.
https://github.com/social-tw/social-tw-website/blob/4951dc4803ccb79df7fdb9ea6e83205310b08c5c/packages/relay/src/services/UserService.ts#L123-L138
  - client side should enable user to post/vote/comment once the user status is on-chain.
  - save user into db on backend side instead of synchronizer.
- PostService
  - the interaction with contract on createPost function can be replaced with `callContract` function.
https://github.com/social-tw/social-tw-website/blob/4951dc4803ccb79df7fdb9ea6e83205310b08c5c/packages/relay/src/services/PostService.ts#L232-L243
  - fetchPost should filter post status, only send posts whose status are on-chain to client side.
  - save post into db on backend side instead of synchronizer.
  - updateOrder should add an addtional contidion to filter posts whose status are on-chain.
