### ISSUE TITLE
Login Backend Tests

### ISSUE THREAD

**Issue by cc03668** [social-tw/social-tw-website#34]
Implement the Backend tests for login and sign-up. The following are the tests we discussed.

- [ ] The backend should have a /signup API.
- [ ] It should accept [sign up proof](https://developer.unirep.io/docs/circuits-api/circuits#signup-proof) and the router should verify it
- [ ] It should accepct Github Oauth information and record the used Github Account.
- [ ] It should return tx success or fail.

**Comment by NOOMA-42** [comment]
@Lisooo790926 Did you modularize `api/user`? If so I can use yours

**Comment by Lisooo790926** [comment]
Yes, I extracted above logic to UserService, so you could test UserService directly
And need your help to review it https://github.com/social-tw/social-tw-website/pull/42
Thanks~

**Comment by NOOMA-42** [comment]
@chentihe These are 2 requests that I record. I'm unable to intercept them. Not sure if it's due to dynamic port when setting up the server.

'''
<<<<<<-- cut here -->>>>>>

nock('https://api.twitter.com:443', {"encodedQueryParams":true})
  .post('/2/oauth2/token')
  .query({"code":"V1N4Nk0wS3A2TGNPV3JYWFNoZHg4bXRHSENLeEZiM25KZWRaMk4xNWFDU0NNOjE2OTI2NjgwMzgxNjg6MTowOmFjOjE","grant_type":"authorization_code","code_verifier":"d2b80725-3938-4fbb-8ea4-9f55f68bed29","client_id":"eDlSQVpZVFlRUmNLa0VMR3NhbTA6MTpjaQ","redirect_uri":"http%3A%2F%2Flocalhost%3A8000%2Fapi%2Fuser"})
  .reply(200, ["1f8b080000000000000074ce4b6b83401486e1bf52661d823a6d4ab36b1b250971ac9351d3d9889763bd456566aa26a1ffbd62a0bbee0e9c17bee786545b4113aa4b07688d62880408b4403076850019160d5a3f1b9ab64051928094e19c4fa5edf15550e98c6d69139ffd4bca6869d72f3dd5d4475cbf4547e6ea3ea63df59475dce62e784f0717db2af679ee94a6e1b09d41caaf816c7698b06465b37674ce9636fda67999b4b3e75b82904b0151faa00600753fdb2cab8b069677d2940bc8266cfe87a39bfd919896c12a9ac7263fa498b4ccf22b4f7f7de45777e4a7caa03e0d3e83aee7efda95e08ea7a70af3d212ffe006a7d9cfb89f5f000000ffff0300cbc8bd8133010000"], [
  'date',
  'Tue, 22 Aug 2023 01:34:02 GMT',
  'perf',
  '7626143928',
  'pragma',
  'no-cache',
  'server',
  'tsa_k',
  'expires',
  'Tue, 31 Mar 1981 05:00:00 GMT',
  'set-cookie',
  'guest_id_marketing=v1%3A169266804220430159; Max-Age=63072000; Expires=Thu, 21 Aug 2025 01:34:02 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
  'set-cookie',
  'guest_id_ads=v1%3A169266804220430159; Max-Age=63072000; Expires=Thu, 21 Aug 2025 01:34:02 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
  'set-cookie',
  'personalization_id="v1_7dBgHDjibpdT3sceyF/Xlg=="; Max-Age=63072000; Expires=Thu, 21 Aug 2025 01:34:02 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
  'set-cookie',
  'guest_id=v1%3A169266804220430159; Max-Age=63072000; Expires=Thu, 21 Aug 2025 01:34:02 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
  'content-type',
  'application/json; charset=utf-8',
  'cache-control',
  'no-cache, no-store, must-revalidate, pre-check=0, post-check=0',
  'last-modified',
  'Tue, 22 Aug 2023 01:34:02 GMT',
  'content-length',
  '265',
  'x-frame-options',
  'SAMEORIGIN',
  'content-encoding',
  'gzip',
  'x-transaction-id',
  'a91fb7af164db966',
  'x-xss-protection',
  '0',
  'content-disposition',
  'attachment; filename=json.json',
  'x-content-type-options',
  'nosniff',
  'x-twitter-response-tags',
  'BouncerCompliant',
  'strict-transport-security',
  'max-age=631138519',
  'x-response-time',
  '714',
  'x-connection-hash',
  '014fc58c551c7cb69941d816cbbd697dee250e039be715dbfca8cc9119eab443',
  'connection',
  'close'
]);
<<<<<<-- cut here -->>>>>>



<<<<<<-- cut here -->>>>>>

nock('https://api.twitter.com:443', {"encodedQueryParams":true})
  .get('/2/users/me')
  .reply(200, ["1f8b0800000000000000aa564a492c4954b2aa56ca4c51b2523234b134b330313130b3b4303530313434303451d251ca4bcc4d054a062496e60079a5c5a9455091bcfcfcdc4413230b33a5da5a00000000ffff03000bed3fbe4a000000"], [
  'date',
  'Tue, 22 Aug 2023 01:34:03 UTC',
  'perf',
  '7626143928',
  'server',
  'tsa_k',
  'set-cookie',
  'guest_id_marketing=v1%3A169266804323301261; Max-Age=63072000; Expires=Thu, 21 Aug 2025 01:34:03 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
  'set-cookie',
  'guest_id_ads=v1%3A169266804323301261; Max-Age=63072000; Expires=Thu, 21 Aug 2025 01:34:03 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
  'set-cookie',
  'personalization_id="v1_/uvFsEVMy3/ZTD71Lsb0JA=="; Max-Age=63072000; Expires=Thu, 21 Aug 2025 01:34:03 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
  'set-cookie',
  'guest_id=v1%3A169266804323301261; Max-Age=63072000; Expires=Thu, 21 Aug 2025 01:34:03 GMT; Path=/; Domain=.twitter.com; Secure; SameSite=None',
  'api-version',
  '2.66',
  'content-type',
  'application/json; charset=utf-8',
  'cache-control',
  'no-cache, no-store, max-age=0',
  'content-length',
  '93',
  'x-access-level',
  'read',
  'x-frame-options',
  'SAMEORIGIN',
  'content-encoding',
  'gzip',
  'x-transaction-id',
  '9fea9a2c45d14061',
  'x-xss-protection',
  '0',
  'x-rate-limit-limit',
  '40000',
  'x-rate-limit-reset',
  '1692668943',
  'content-disposition',
  'attachment; filename=json.json',
  'x-content-type-options',
  'nosniff',
  'x-rate-limit-remaining',
  '39999',
  'strict-transport-security',
  'max-age=631138519',
  'x-user-limit-24hour-limit',
  '25',
  'x-user-limit-24hour-reset',
  '1692750307',
  'x-user-limit-24hour-remaining',
  '23',
  'x-response-time',
  '200',
  'x-connection-hash',
  '39b246826d2d5ad98a0ddb1e945a29b999218b55cb6dcf2f5799a97841a03121',
  'connection',
  'close'
]);
<<<<<<-- cut here -->>>>>>

'''

**Comment by NOOMA-42** [comment]
@chentihe CALLBACK_URL is hardcoded to 8000 port but testing port is dynamic. that's why nock intercept no request
```
export const CALLBACK_URL =
    process.env.CALLBACK_URL ?? 'http://localhost:8000/api/user'
```

**Comment by NOOMA-42** [comment]
It seems I've intercepted all the request but I stuck at this line. Error message doesn't show properly  
https://github.com/social-tw/social-tw-website/blob/test/login-relay/packages/relay/src/routes/user.ts#L36

**Comment by ryanycw** [comment]
> @chentihe CALLBACK_URL is hardcoded to 8000 port but testing port is dynamic. that's why nock intercept no request
> 
> I'll change testing port config to 8000 
> 
> @ryanycw any drawback to hardcode testing port config to 8000?
> 
> ```
> 
> export const CALLBACK_URL =
> 
>     process.env.CALLBACK_URL ?? 'http://localhost:8000/api/user'
> 
> ```

I am not sure if I'm following here. But yes it uses dynamic port every time so it should be an issue using a hardcoded port. In the test/configs.ts we used get port to get the right port.

**Comment by ryanycw** [comment]
This issue should be close by #47
