### ISSUE TITLE
[UST-166][Contract] Claim Negative Reputation

### ISSUE THREAD

**Issue by ryanycw** [social-tw/social-tw-website#378]
**Is your feature request related to a problem? Please describe.**
Implement a new function to claim negative reputation after the report is being agreed.

**Describe the solution you'd like**
This function should receive transaction to attest negative reputation to reported person or reporter accordingly.

**Related Issues**
- Claim Negative Reputation (Circuit)
- Claim Positive Reputation (Contract)

**Todos**
- [ ] Implement function `claimReportRep` 

**Tests**
- Should success claim negative reputation
- Should revert with used proof
- Should revert if Epks doesn't come from same user
- Should revert if the postId or commentId doesn't match

**Comment by FoodChain1028** [comment]
Hi @ryanycw, there might be 2 situation that a user might get negative reputations:

1. the poster's post got reported && the report is agreed. (-5)
2. the reporter generated a report but the report is failed. (-1)

I think this issue is currently for the first condition. maybe we can add a parameter to determine which situation is.

i.e. 
```solidity
bool reportParam 
// true: poster
// false: reporter
if (reportParam) {
// -5
} else {
// -1
}
```
